apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: go-webapp-sample-il7h
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: go-webapp-sample-il7h
    app.kubernetes.io/part-of: gws
  name: go-webapp-sample-il7h
  namespace: pmacik-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: go-webapp-sample-il7h
    weight: null
status: {}
