apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: go-webapp-sample-il7h
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: go-webapp-sample-il7h
    app.kubernetes.io/part-of: gws
  name: go-webapp-sample-il7h
  namespace: pmacik-tenant
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: go-webapp-sample-il7h
status:
  loadBalancer: {}
